### ISSUE TITLE
base16-eighties green and yellow are just variants of gray

### ISSUE THREAD

**Issue by jedahan** [aaron-williamson/base16-alacritty#2]
Wondering if this was a generation or input data issue?

**Comment by aarowill** [comment]
Are you sure you aren't talking about *bright* green/yellow? Because the bright colors are used for more base (blacks/greys/whites) colors by base16. If you're unsure, try the [eighties-256 file](https://github.com/aaron-williamson/base16-alacritty/blob/master/colors/base16-eighties-256.yml). The bright colors match their dim counterparts so when you're expecting green or bright green you'll always get green, but you'll need to use [base16-shell](https://github.com/chriskempson/base16-shell) to get everything to work properly with programs like vim.

**Comment by jedahan** [comment]
ahh thanks for the clarification!

**Comment by tonijarjour** [comment]
So the bright green is _intended_ to look grey in the non-256 version? Does `TERM= xterm-256color` have anything to do with it?
![2018-11-27_08-56](https://user-images.githubusercontent.com/39845673/49069962-7923cf80-f222-11e8-833d-0519ef3ee700.png)
.fehbg ends up very low contrast. I can live with it if it is intended and doesn't affect too many things.

**Comment by tonijarjour** [comment]
I'll just note that setting this: `draw_bold_text_with_bright_colors: false` fixes the issue.

**Comment by aarowill** [comment]
Yes, @tonijarjour, bright green is meant to be grey in the non-256 version. The reason `draw_bold_text_with_bright_colors: false` fixes this is because you end up with non-bright colors for the bold text (in your screenshot `Downloads, .cache, .config, .fehbg, .gitconfig`). An example from my own terminal (iTerm2, draw bold text in bright colors off, base16-summerfruit-dark theme) showing normal colors next to their bright counterparts: 

<img width="671" alt="image" src="https://user-images.githubusercontent.com/9038848/49096246-6c55aa80-f227-11e8-9e77-12479fc21fc8.png">

A one-liner to show this comparison that should work on most setups: 
```bash
echo " Normal   Bright"; for num in {0..7}; do echo -e "\e[37;$((40 + num))m        \e[39;49m \e[37;$((num + 100))m        \e[39;49m"; done
```
