### ISSUE TITLE
Different colors in comparison to other base16 colorschemes

### ISSUE THREAD

**Issue by okraits** [aaron-williamson/base16-alacritty#9]
I noticed that these base16 colorschemes for alacritty have some different colors in comparison to the base16 colorschemes for xfce4-terminal: https://github.com/tinted-theming/base16-xfce4-terminal

The difference is noticeable in several themes, if not all. Let me show with some screenshots.
On the left: xfc4-terminal On the right: alacritty

![grafik](https://github.com/aarowill/base16-alacritty/assets/5543887/33aac6f5-d93b-408c-baca-868c89ad9107)
Theme: base16-bright

![grafik](https://github.com/aarowill/base16-alacritty/assets/5543887/2067f291-fc34-4181-aa71-58c9b1e832b0)
Theme: base16-selenized-black

![grafik](https://github.com/aarowill/base16-alacritty/assets/5543887/2852a3dc-fd1d-4eeb-8ebc-0ea65c4e3ad0)
Theme: base16-tomorrow-night

Could this be caused by some setting on my side or is it in the colorschemes?

**Comment by aarowill** [comment]
It looks like the xfce theme defaults to the 256 variants: [some info on this in the README](https://github.com/aarowill/base16-alacritty/tree/63d8ae5dfefe5db825dd4c699d0cdc2fc2c3eaf7#256-variations). If you want the themes to look like they do in the left-hand xfce4 examples, try using the <theme>-256 config instead, for example use [base16-bright-256.yml](https://github.com/aarowill/base16-alacritty/blob/63d8ae5dfefe5db825dd4c699d0cdc2fc2c3eaf7/colors/base16-bright-256.yml) instead of base16-bright.yml

**Comment by okraits** [comment]
Thank you for the explanation. I will try it out.
